### ISSUE TITLE
Running setup.py install for cchardet ... error

### ISSUE THREAD

**Issue by peterchanws** [webrecorder/warcit#21]
Here is the log:
Collecting warcit
  Using cached https://files.pythonhosted.org/packages/fc/1a/df5a9ec994860bf4e557e6a754b9347d060cd5daffadebb8f2a7ad83b88a/warcit-0.4.0-py2.py3-none-any.whl
Requirement already satisfied: warcio>=1.6.1 in /Library/Python/2.7/site-packages (from warcit) (1.7.4)
Requirement already satisfied: pyyaml in /Library/Python/2.7/site-packages (from warcit) (5.4.1)
Collecting cchardet (from warcit)
  Using cached https://files.pythonhosted.org/packages/a8/5d/090c9f0312b7988a9433246c9cf0b566b1ae1374368cfb8ac897218a4f65/cchardet-2.1.7.tar.gz
Requirement already satisfied: six in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from warcio>=1.6.1->warcit) (1.12.0)
Building wheels for collected packages: cchardet
  Building wheel for cchardet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/m0/qcfbp8m139x_7s7h08y9176c0000gq/T/pip-install-oFw6xI/cchardet/setup.py'"'"'; __file__='"'"'/private/var/folders/m0/qcfbp8m139x_7s7h08y9176c0000gq/T/pip-install-oFw6xI/cchardet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/m0/qcfbp8m139x_7s7h08y9176c0000gq/T/pip-wheel-61jwa9 --python-tag cp27
       cwd: /private/var/folders/m0/qcfbp8m139x_7s7h08y9176c0000gq/T/pip-install-oFw6xI/cchardet/
  Complete output (20 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-11.4-x86_64-2.7
  creating build/lib.macosx-11.4-x86_64-2.7/cchardet
  copying src/cchardet/version.py -> build/lib.macosx-11.4-x86_64-2.7/cchardet
  copying src/cchardet/__init__.py -> build/lib.macosx-11.4-x86_64-2.7/cchardet
  running build_ext
  building 'cchardet._cchardet' extension
  creating build/temp.macosx-11.4-x86_64-2.7
  creating build/temp.macosx-11.4-x86_64-2.7/src
  creating build/temp.macosx-11.4-x86_64-2.7/src/cchardet
  creating build/temp.macosx-11.4-x86_64-2.7/src/ext
  creating build/temp.macosx-11.4-x86_64-2.7/src/ext/uchardet
  creating build/temp.macosx-11.4-x86_64-2.7/src/ext/uchardet/src
  creating build/temp.macosx-11.4-x86_64-2.7/src/ext/uchardet/src/LangModels
  cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wshorten-64-to-32 -iwithsysroot /usr/local/libressl/include -DNDEBUG -g -fwrapv -Os -Wall -DENABLE_DTRACE -pipe -Isrc/ext/uchardet/src -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/cchardet/_cchardet.cpp -o build/temp.macosx-11.4-x86_64-2.7/src/cchardet/_cchardet.o
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command 'cc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for cchardet
  Running setup.py clean for cchardet
Failed to build cchardet
Installing collected packages: cchardet, warcit
  Running setup.py install for cchardet ... error
    ERROR: Command errored out with exit status 1:
     command: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/m0/qcfbp8m139x_7s7h08y9176c0000gq/T/pip-install-oFw6xI/cchardet/setup.py'"'"'; __file__='"'"'/private/var/folders/m0/qcfbp8m139x_7s7h08y9176c0000gq/T/pip-install-oFw6xI/cchardet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/m0/qcfbp8m139x_7s7h08y9176c0000gq/T/pip-record-MJbEuR/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/m0/qcfbp8m139x_7s7h08y9176c0000gq/T/pip-install-oFw6xI/cchardet/
    Complete output (20 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-11.4-x86_64-2.7
    creating build/lib.macosx-11.4-x86_64-2.7/cchardet
    copying src/cchardet/version.py -> build/lib.macosx-11.4-x86_64-2.7/cchardet
    copying src/cchardet/__init__.py -> build/lib.macosx-11.4-x86_64-2.7/cchardet
    running build_ext
    building 'cchardet._cchardet' extension
    creating build/temp.macosx-11.4-x86_64-2.7
    creating build/temp.macosx-11.4-x86_64-2.7/src
    creating build/temp.macosx-11.4-x86_64-2.7/src/cchardet
    creating build/temp.macosx-11.4-x86_64-2.7/src/ext
    creating build/temp.macosx-11.4-x86_64-2.7/src/ext/uchardet
    creating build/temp.macosx-11.4-x86_64-2.7/src/ext/uchardet/src
    creating build/temp.macosx-11.4-x86_64-2.7/src/ext/uchardet/src/LangModels
    cc -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wshorten-64-to-32 -iwithsysroot /usr/local/libressl/include -DNDEBUG -g -fwrapv -Os -Wall -DENABLE_DTRACE -pipe -Isrc/ext/uchardet/src -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/cchardet/_cchardet.cpp -o build/temp.macosx-11.4-x86_64-2.7/src/cchardet/_cchardet.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command 'cc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/m0/qcfbp8m139x_7s7h08y9176c0000gq/T/pip-install-oFw6xI/cchardet/setup.py'"'"'; __file__='"'"'/private/var/folders/m0/qcfbp8m139x_7s7h08y9176c0000gq/T/pip-install-oFw6xI/cchardet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/m0/qcfbp8m139x_7s7h08y9176c0000gq/T/pip-record-MJbEuR/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by luroset** [comment]
Hi, how did you resolve this issue? Thanks!
