### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by tim-moody** [webrecorder/warcit#3]
Sorry, warcit requires python >= 3.4, you are running 2.7.13

/usr/local/bin/warcit should have python3

**Comment by ikreymer** [comment]
hi, just saw this.. yes, the current version of warcit requires python >= 3.4.. this is the error that you see if you've installed it under python 2.7..

are you saying that you installed it with python 3 and you are getting this error?

**Comment by tim-moody** [comment]
I'm saying 2 things. 

1) Your docs did not give syntax for a  python 3 install when both 2.7 an 3.x are present (which I think  is always the case)

2) /usr/local/bin/warcit should have python3 instead of python at the top or it will  try to execute under 2.7 and issue the error message

**Comment by ikreymer** [comment]
Turns out its not too bad to add 2.7 support, so will just do that.

Yes, the docs don't mention the version.

But, `/usr/local/bin/warcit` is generated automatically by setuptools and I believe it users whatever version it was installed with.

**Comment by tim-moody** [comment]
my memory is that I first installed with pip, following the docs, and then after the error with pip3, but probably /usr/local/bin/warcit was already installed and not overwritten.
